package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private Integer idDetaC;
     private Notacompra notacompra;
     private int cantidad;
     private float precioXcant;
     private Integer idProducto;
     private Set productos = new HashSet(0);

    public Detallecompra() {
    }

	
    public Detallecompra(int cantidad, float precioXcant) {
        this.cantidad = cantidad;
        this.precioXcant = precioXcant;
    }
    public Detallecompra(Notacompra notacompra, int cantidad, float precioXcant, Integer idProducto, Set productos) {
       this.notacompra = notacompra;
       this.cantidad = cantidad;
       this.precioXcant = precioXcant;
       this.idProducto = idProducto;
       this.productos = productos;
    }
   
    public Integer getIdDetaC() {
        return this.idDetaC;
    }
    
    public void setIdDetaC(Integer idDetaC) {
        this.idDetaC = idDetaC;
    }
    public Notacompra getNotacompra() {
        return this.notacompra;
    }
    
    public void setNotacompra(Notacompra notacompra) {
        this.notacompra = notacompra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public float getPrecioXcant() {
        return this.precioXcant;
    }
    
    public void setPrecioXcant(float precioXcant) {
        this.precioXcant = precioXcant;
    }
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


