package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private Integer idDetalleV;
     private Notaventa notaventa;
     private Producto producto;
     private float precio;

    public Detalleventa() {
    }

	
    public Detalleventa(float precio) {
        this.precio = precio;
    }
    public Detalleventa(Notaventa notaventa, Producto producto, float precio) {
       this.notaventa = notaventa;
       this.producto = producto;
       this.precio = precio;
    }
   
    public Integer getIdDetalleV() {
        return this.idDetalleV;
    }
    
    public void setIdDetalleV(Integer idDetalleV) {
        this.idDetalleV = idDetalleV;
    }
    public Notaventa getNotaventa() {
        return this.notaventa;
    }
    
    public void setNotaventa(Notaventa notaventa) {
        this.notaventa = notaventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }




}


