package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notaventa generated by hbm2java
 */
public class Notaventa  implements java.io.Serializable {


     private Integer idNotaVenta;
     private Cliente cliente;
     private Date fechaHora;
     private Set detalleventas = new HashSet(0);

    public Notaventa() {
    }

	
    public Notaventa(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Notaventa(Cliente cliente, Date fechaHora, Set detalleventas) {
       this.cliente = cliente;
       this.fechaHora = fechaHora;
       this.detalleventas = detalleventas;
    }
   
    public Integer getIdNotaVenta() {
        return this.idNotaVenta;
    }
    
    public void setIdNotaVenta(Integer idNotaVenta) {
        this.idNotaVenta = idNotaVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


