package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notacompra generated by hbm2java
 */
public class Notacompra  implements java.io.Serializable {


     private Integer idCompra;
     private Proveedor proveedor;
     private Usuario usuario;
     private Date fecha;
     private Set detallecompras = new HashSet(0);

    public Notacompra() {
    }

	
    public Notacompra(Date fecha) {
        this.fecha = fecha;
    }
    public Notacompra(Proveedor proveedor, Usuario usuario, Date fecha, Set detallecompras) {
       this.proveedor = proveedor;
       this.usuario = usuario;
       this.fecha = fecha;
       this.detallecompras = detallecompras;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


