package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private Detallecompra detallecompra;
     private String nombre;
     private float precio;
     private Set detalleventas = new HashSet(0);
     private Set tiendaSucursals = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombre, float precio) {
        this.nombre = nombre;
        this.precio = precio;
    }
    public Producto(Categoria categoria, Detallecompra detallecompra, String nombre, float precio, Set detalleventas, Set tiendaSucursals) {
       this.categoria = categoria;
       this.detallecompra = detallecompra;
       this.nombre = nombre;
       this.precio = precio;
       this.detalleventas = detalleventas;
       this.tiendaSucursals = tiendaSucursals;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Detallecompra getDetallecompra() {
        return this.detallecompra;
    }
    
    public void setDetallecompra(Detallecompra detallecompra) {
        this.detallecompra = detallecompra;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set getTiendaSucursals() {
        return this.tiendaSucursals;
    }
    
    public void setTiendaSucursals(Set tiendaSucursals) {
        this.tiendaSucursals = tiendaSucursals;
    }

    @Override
    public String toString() {
        return this.nombre;
    }




}


