package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombre;
     private Set notacompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre) {
        this.nombre = nombre;
    }
    public Proveedor(String nombre, Set notacompras) {
       this.nombre = nombre;
       this.notacompras = notacompras;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getNotacompras() {
        return this.notacompras;
    }
    
    public void setNotacompras(Set notacompras) {
        this.notacompras = notacompras;
    }




}


