package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1



/**
 * TiendaSucursal generated by hbm2java
 */
public class TiendaSucursal  implements java.io.Serializable {


     private Integer idTienda;
     private Producto producto;
     private String nombre;
     private String ubicacion;

    public TiendaSucursal() {
    }

	
    public TiendaSucursal(String nombre, String ubicacion) {
        this.nombre = nombre;
        this.ubicacion = ubicacion;
    }
    public TiendaSucursal(Producto producto, String nombre, String ubicacion) {
       this.producto = producto;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
    }
   
    public Integer getIdTienda() {
        return this.idTienda;
    }
    
    public void setIdTienda(Integer idTienda) {
        this.idTienda = idTienda;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }




}


