package compraventamvc1.modelo.datos;
// Generated 12-abr-2015 14:39:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String loggin;
     private String password;
     private Set notacompras = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String loggin, String password) {
        this.nombre = nombre;
        this.loggin = loggin;
        this.password = password;
    }
    public Usuario(String nombre, String loggin, String password, Set notacompras) {
       this.nombre = nombre;
       this.loggin = loggin;
       this.password = password;
       this.notacompras = notacompras;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLoggin() {
        return this.loggin;
    }
    
    public void setLoggin(String loggin) {
        this.loggin = loggin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getNotacompras() {
        return this.notacompras;
    }
    
    public void setNotacompras(Set notacompras) {
        this.notacompras = notacompras;
    }




}


