/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compraventamvc1.vista;

/**
 *
 * @author Lion
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnusuario = new javax.swing.JButton();
        btncompra = new javax.swing.JButton();
        btncategoria = new javax.swing.JButton();
        btnproducto = new javax.swing.JButton();
        btncliente = new javax.swing.JButton();
        btnproveedor = new javax.swing.JButton();
        btntraspaso = new javax.swing.JButton();
        btnsucursal = new javax.swing.JButton();
        btnventa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btnusuario.setBackground(new java.awt.Color(255, 255, 255));
        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/USUARIO.png"))); // NOI18N
        btnusuario.setText("Usuario");
        btnusuario.setMaximumSize(new java.awt.Dimension(83, 23));
        btnusuario.setMinimumSize(new java.awt.Dimension(83, 23));
        btnusuario.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btnusuario);

        btncompra.setBackground(new java.awt.Color(255, 255, 255));
        btncompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/COMPRA.png"))); // NOI18N
        btncompra.setText("Compra");
        btncompra.setMaximumSize(new java.awt.Dimension(83, 23));
        btncompra.setMinimumSize(new java.awt.Dimension(83, 23));
        btncompra.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btncompra);

        btncategoria.setBackground(new java.awt.Color(255, 255, 255));
        btncategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/CATEGORIA.png"))); // NOI18N
        btncategoria.setText("Categoria");
        btncategoria.setMaximumSize(new java.awt.Dimension(83, 23));
        btncategoria.setMinimumSize(new java.awt.Dimension(83, 23));
        btncategoria.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btncategoria);

        btnproducto.setBackground(new java.awt.Color(255, 255, 255));
        btnproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/PRODUCTO.png"))); // NOI18N
        btnproducto.setText("Producto");
        btnproducto.setMaximumSize(new java.awt.Dimension(83, 23));
        btnproducto.setMinimumSize(new java.awt.Dimension(83, 23));
        btnproducto.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btnproducto);

        btncliente.setBackground(new java.awt.Color(255, 255, 255));
        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/CLIENTE.png"))); // NOI18N
        btncliente.setText("Cliente");
        btncliente.setMaximumSize(new java.awt.Dimension(83, 23));
        btncliente.setMinimumSize(new java.awt.Dimension(83, 23));
        btncliente.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btncliente);

        btnproveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/PROVEEDOR.png"))); // NOI18N
        btnproveedor.setText("Proveedor");
        jPanel1.add(btnproveedor);

        btntraspaso.setBackground(new java.awt.Color(255, 255, 255));
        btntraspaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/TRASPASO.png"))); // NOI18N
        btntraspaso.setText("Contacto");
        btntraspaso.setMaximumSize(new java.awt.Dimension(83, 23));
        btntraspaso.setMinimumSize(new java.awt.Dimension(83, 23));
        btntraspaso.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btntraspaso);

        btnsucursal.setBackground(new java.awt.Color(255, 255, 255));
        btnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/SUCURSAL.png"))); // NOI18N
        btnsucursal.setText("Sucursal");
        btnsucursal.setMaximumSize(new java.awt.Dimension(83, 23));
        btnsucursal.setMinimumSize(new java.awt.Dimension(83, 23));
        btnsucursal.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btnsucursal);

        btnventa.setBackground(new java.awt.Color(255, 255, 255));
        btnventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compraventamvc1/modelo/recursos/VENTA.png"))); // NOI18N
        btnventa.setText("Venta");
        btnventa.setMaximumSize(new java.awt.Dimension(83, 23));
        btnventa.setMinimumSize(new java.awt.Dimension(83, 23));
        btnventa.setPreferredSize(new java.awt.Dimension(83, 23));
        jPanel1.add(btnventa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncategoria;
    public javax.swing.JButton btncliente;
    public javax.swing.JButton btncompra;
    public javax.swing.JButton btnproducto;
    public javax.swing.JButton btnproveedor;
    private javax.swing.JButton btnsucursal;
    private javax.swing.JButton btntraspaso;
    public javax.swing.JButton btnusuario;
    public javax.swing.JButton btnventa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
